---
kind: pipeline
type: kubernetes
name: default

environment:
  GOCACHE: /cache/pkg/cache
  GOMODCACHE: /cache/pkg/mod

steps:
  - name: fetch-tags
    image: alpine/git
    commands:
      - git fetch --tags
    resources:
      requests:
        cpu: 250
        memory: 50MiB
      limits:
        cpu: 250
        memory: 100MiB

  - name: test
    image: golang:1.20.4
    volumes:
      - name: go
        path: /go
      - name: gopkg
        path: /cache
    commands:
      - go test -v ./...
      - go build ./...
    resources:
      requests:
        cpu: 1000
        memory: 128MiB
      limits:
        cpu: 2000
        memory: 2GiB

  - name: goreleaser
    image: golang:1.20.4
    resources:
      requests:
        cpu: 4000
        memory: 1024MiB
      limits:
        cpu: 10000
        memory: 4096MiB
    volumes:
      - name: go
        path: /go
      - name: gopkg
        path: /cache
    commands:
      # curl -sf https://goreleaser.com/static/latest
      - go install github.com/goreleaser/goreleaser@v1.18.2
      - ./scripts/run-goreleaser
      - echo Done
    depends_on: [test]

  - name: docker
    image: harbor.ntppool.org/ntppool/drone-kaniko:main
    pull: always
    settings:
      repo: ntppool/monitor-api
      registry: harbor.ntppool.org
      tags: "${DRONE_BRANCH},build-${DRONE_BUILD_NUMBER},SHAABBREV,SHA7"
      auto_tag: true
      cache: true
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
    depends_on: [goreleaser]

  - name: upload
    image: plugins/s3
    resources:
      requests:
        cpu: 250
        memory: 64MiB
      limits:
        cpu: 250
        memory: 256MiB
    settings:
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key
      bucket: geodns
      target: /monitor/builds/${DRONE_BUILD_NUMBER}
      source: dist/*
      strip_prefix: dist/
      endpoint: https://minio-ewr1.develooper.com/
      path_style: true
    when:
      ref:
        - refs/heads/main
        - refs/tags/*
    depends_on: [goreleaser]

  - name: fury-publish
    image: golang:1.20.4
    resources:
      requests:
        cpu: 250
        memory: 64MiB
      limits:
        cpu: 250
        memory: 256MiB
    environment:
      FURY_TOKEN:
        from_secret: fury_test_token
    commands:
      - ./scripts/fury-publish ntppool-test
    when:
      ref:
        - refs/heads/main
        - refs/tags/*
    depends_on: [goreleaser]

volumes:
  - name: go
    temp: {}
  - name: gopkg
    claim:
      name: go-pkg

trigger:
  event:
    - push
    - tag
    - pull_request

---
kind: pipeline
type: kubernetes
name: publish-production

steps:
  - name: download
    image: golang:1.20.4
    commands:
      - ./scripts/download-release ${DRONE_BUILD_PARENT} dist/
    resources:
      requests:
        cpu: 250
        memory: 64MiB
      limits:
        cpu: 250
        memory: 256MiB

  - name: fury-publish
    image: golang:1.20.4
    resources:
      requests:
        cpu: 250
        memory: 64MiB
      limits:
        cpu: 250
        memory: 256MiB
    environment:
      FURY_TOKEN:
        from_secret: fury_token
    commands:
      - ./scripts/fury-publish ntppool
    depends_on: ["download"]

trigger:
  event:
    - promote
  target:
    - publish
---
kind: signature
hmac: 8356269e8809071ea9404476a3e692493b0d830922babb38ebe44b70189cbc55

...
