# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - main: ./cmd/ntppool-agent/
    id: ntppool-agent
    binary: ntppool-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - riscv64
    ldflags:
      - -s -w
      - -X go.ntppool.org/common/version.VERSION={{.Version}}

  - main: ./cmd/monitor-api/
    id: monitor-api
    binary: monitor-api
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w
      - -X go.ntppool.org/common/version.VERSION={{.Version}}

  - main: ./cmd/monitor-scorer/
    id: monitor-scorer
    binary: monitor-scorer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    ldflags:
      - -s -w
      - -X go.ntppool.org/common/version.VERSION={{.Version}}

archives:
  - id: a1
    ids:
    - ntppool-agent
    name_template: "ntppool-agent_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    allow_different_binary_count: true
  # files:
  #   - LICENSE.txt
  #   - ./client/cmd/ntppool-monitor/README.md

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: '{{ .Tag }}{{ if index .Env "DRONE_BUILD_NUMBER" }}-{{ .Env.DRONE_BUILD_NUMBER }}{{ else }}-next{{ end }}'
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: ntppool-agent

    package_name: ntppool-agent

    ids:
      - ntppool-agent

    #file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    file_name_template: "{{ .ConventionalFileName }}"

    vendor: NTP Pool Project
    homepage: https://www.ntppool.org/
    maintainer: Ask Bjørn Hansen <ask@develooper.com>
    description: Monitoring daemon for the NTP Pool
    license: Apache 2.0
    formats:
      - deb
      - rpm
      - apk
    dependencies:
      - chrony
    bindir: /usr/bin

    overrides:
      deb:
        dependencies:
          - "ntp | chrony | ntpsec | ntpd-rs"

      rpm:
        # this is supposed to work, but I couldn't figure it out.
        # so, ... chrony only on redhat flavors for now.
        #dependencies:
        #  - (ntp or chrony)

    contents:
      - src: "scripts/ntppool-agent@.service"
        dst: "/etc/systemd/system/ntppool-agent@.service"

      #- src: "scripts/enable-ntppool-monitors"
      #  dst: "/usr/bin/enable-ntppool-monitors"

      - src: "scripts/defaults"
        dst: "/etc/default/ntppool-agent.sample"
        type: config

      - src: "scripts/defaults"
        dst: "/etc/default/ntppool-agent"
        type: config|noreplace

      - src: "man/ntppool-agent.1"
        dst: "/usr/share/man/man1/ntppool-agent.1"

    scripts:
      preinstall: scripts/preinstall.sh
      postinstall: scripts/postinstall.sh
