# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - main: ./cmd/ntppool-agent/
    id: ntppool-agent
    binary: ntppool-agent
    env:
      - CGO_ENABLED=0
      # https://community.ntppool.org/t/ntp-pool-agent-v4-0-2/3998/2
      - GO386=softfloat
    goos:
      - linux
      - freebsd
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - 386
      - riscv64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: amd64

    ldflags:
      - -s -w
      - -X go.ntppool.org/common/version.VERSION={{.Version}}
      - -X go.ntppool.org/common/version.buildTime={{.Timestamp}}

  - main: ./cmd/monitor-api/
    id: monitor-api
    binary: monitor-api
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64_v2
      - darwin_arm64

    ldflags:
      - -s -w
      - -X go.ntppool.org/common/version.VERSION={{.Version}}
      - -X go.ntppool.org/common/version.buildTime={{.Timestamp}}

  - main: ./cmd/monitor-scorer/
    id: monitor-scorer
    binary: monitor-scorer
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64_v2
      - darwin_arm64
    ldflags:
      - -s -w
      - -X go.ntppool.org/common/version.VERSION={{.Version}}
      - -X go.ntppool.org/common/version.buildTime={{.Timestamp}}

before:
  # Templates for the commands to be ran.
  hooks:
  - ./scripts/update-man-page

archives:
  - id: a1
    ids:
    - ntppool-agent
    name_template: "ntppool-agent_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    allow_different_binary_count: true
  # files:
  #   - LICENSE.txt
  #   - ./client/cmd/ntppool-monitor/README.md

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: '{{ .Tag }}{{ if index .Env "DRONE_BUILD_NUMBER" }}-{{ .Env.DRONE_BUILD_NUMBER }}{{ else }}-next{{ end }}'
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: ntppool-agent

    package_name: ntppool-agent

    ids:
      - ntppool-agent

    #file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    file_name_template: "{{ .ConventionalFileName }}"

    vendor: NTP Pool Project
    homepage: https://www.ntppool.org/
    maintainer: Ask Bjørn Hansen <ask@develooper.com>
    description: Monitoring daemon for the NTP Pool
    license: Apache 2.0
    formats:
      - deb
      - rpm
      - apk
    # No global dependencies - each format specifies its own
    bindir: /usr/bin

    overrides:
      deb:
        dependencies:
          - "ntp | chrony | ntpsec | ntpd-rs"

      rpm:
        dependencies:
          - "(ntp or chrony or ntpsec or ntpd-rs)"

      apk:
        # Alpine Linux doesn't have a virtual package for NTP services like
        # "ntp-daemon" that multiple implementations can provide. Users should
        # manually install one of: chrony, openntpd, ntpsec, or ntpd-rs
        dependencies: []

    contents:
      - src: "scripts/ntppool-agent@.service"
        dst: "/etc/systemd/system/ntppool-agent@.service"

      #- src: "scripts/enable-ntppool-monitors"
      #  dst: "/usr/bin/enable-ntppool-monitors"

      - src: "scripts/defaults"
        dst: "/etc/default/ntppool-agent.sample"
        type: config

      - src: "scripts/defaults"
        dst: "/etc/default/ntppool-agent"
        type: config|noreplace

      - src: "man/ntppool-agent.1"
        dst: "/usr/share/man/man1/ntppool-agent.1"

    scripts:
      preinstall: scripts/preinstall.sh
      postinstall: scripts/postinstall.sh
