FROM golang:1.19.3-alpine AS build

ADD . /go/src/monitor/
WORKDIR /go/src/monitor
RUN go install -v ./...

FROM alpine:3.16.2

#RUN apk --no-cache add ca-certificates tzdata zsh jq tmux curl go
RUN apk --no-cache add ca-certificates tzdata zsh jq tmux curl
RUN apk --no-cache upgrade --ignore alpine-baselayout

RUN addgroup -g 1000 ntpmon && adduser -u 1000 -D -G ntpmon ntpmon
RUN touch ~ntpmon/.zshrc ~root/.zshrc; chown ntpmon:ntpmon ~ntpmon/.zshrc

RUN mkdir /app
COPY --from=build /go/bin/monitor-api /app/
COPY --from=build /go/bin/ntppool-monitor /app/
COPY --from=build /go/bin/monitor-scorer /app/

EXPOSE 8000
EXPOSE 8080

USER ntpmon

# Container start command for production
CMD ["/app/monitor-api"]
