// Code generated by "stringer -type=candidateStatus"; DO NOT EDIT.

package cmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[candidateUnknown-0]
	_ = x[candidateIn-1]
	_ = x[candidateOut-2]
	_ = x[candidateBlock-3]
}

const _candidateStatus_name = "candidateUnknowncandidateIncandidateOutcandidateBlock"

var _candidateStatus_index = [...]uint8{0, 16, 27, 39, 53}

func (i candidateState) String() string {
	if i >= candidateState(len(_candidateStatus_index)-1) {
		return "candidateStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _candidateStatus_name[_candidateStatus_index[i]:_candidateStatus_index[i+1]]
}
