// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ntpdb

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MonitorsIpVersion string

const (
	MonitorsIpVersionV4 MonitorsIpVersion = "v4"
	MonitorsIpVersionV6 MonitorsIpVersion = "v6"
)

func (e *MonitorsIpVersion) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MonitorsIpVersion(s)
	case string:
		*e = MonitorsIpVersion(s)
	default:
		return fmt.Errorf("unsupported scan type for MonitorsIpVersion: %T", src)
	}
	return nil
}

type NullMonitorsIpVersion struct {
	MonitorsIpVersion MonitorsIpVersion `json:"monitors_ip_version"`
	Valid             bool              `json:"valid"` // Valid is true if MonitorsIpVersion is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMonitorsIpVersion) Scan(value interface{}) error {
	if value == nil {
		ns.MonitorsIpVersion, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MonitorsIpVersion.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMonitorsIpVersion) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MonitorsIpVersion), nil
}

type MonitorsStatus string

const (
	MonitorsStatusPending MonitorsStatus = "pending"
	MonitorsStatusTesting MonitorsStatus = "testing"
	MonitorsStatusActive  MonitorsStatus = "active"
	MonitorsStatusPaused  MonitorsStatus = "paused"
	MonitorsStatusDeleted MonitorsStatus = "deleted"
)

func (e *MonitorsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MonitorsStatus(s)
	case string:
		*e = MonitorsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MonitorsStatus: %T", src)
	}
	return nil
}

type NullMonitorsStatus struct {
	MonitorsStatus MonitorsStatus `json:"monitors_status"`
	Valid          bool           `json:"valid"` // Valid is true if MonitorsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMonitorsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MonitorsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MonitorsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMonitorsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MonitorsStatus), nil
}

type MonitorsType string

const (
	MonitorsTypeMonitor MonitorsType = "monitor"
	MonitorsTypeScore   MonitorsType = "score"
)

func (e *MonitorsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MonitorsType(s)
	case string:
		*e = MonitorsType(s)
	default:
		return fmt.Errorf("unsupported scan type for MonitorsType: %T", src)
	}
	return nil
}

type NullMonitorsType struct {
	MonitorsType MonitorsType `json:"monitors_type"`
	Valid        bool         `json:"valid"` // Valid is true if MonitorsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMonitorsType) Scan(value interface{}) error {
	if value == nil {
		ns.MonitorsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MonitorsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMonitorsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MonitorsType), nil
}

type ServerScoresStatus string

const (
	ServerScoresStatusCandidate ServerScoresStatus = "candidate"
	ServerScoresStatusTesting   ServerScoresStatus = "testing"
	ServerScoresStatusActive    ServerScoresStatus = "active"
	ServerScoresStatusPaused    ServerScoresStatus = "paused"
)

func (e *ServerScoresStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ServerScoresStatus(s)
	case string:
		*e = ServerScoresStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ServerScoresStatus: %T", src)
	}
	return nil
}

type NullServerScoresStatus struct {
	ServerScoresStatus ServerScoresStatus `json:"server_scores_status"`
	Valid              bool               `json:"valid"` // Valid is true if ServerScoresStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullServerScoresStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ServerScoresStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ServerScoresStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullServerScoresStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ServerScoresStatus), nil
}

type ServersIpVersion string

const (
	ServersIpVersionV4 ServersIpVersion = "v4"
	ServersIpVersionV6 ServersIpVersion = "v6"
)

func (e *ServersIpVersion) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ServersIpVersion(s)
	case string:
		*e = ServersIpVersion(s)
	default:
		return fmt.Errorf("unsupported scan type for ServersIpVersion: %T", src)
	}
	return nil
}

type NullServersIpVersion struct {
	ServersIpVersion ServersIpVersion `json:"servers_ip_version"`
	Valid            bool             `json:"valid"` // Valid is true if ServersIpVersion is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullServersIpVersion) Scan(value interface{}) error {
	if value == nil {
		ns.ServersIpVersion, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ServersIpVersion.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullServersIpVersion) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ServersIpVersion), nil
}

type Account struct {
	ID               int64              `json:"id"`
	IDToken          pgtype.Text        `json:"id_token"`
	Name             pgtype.Text        `json:"name"`
	OrganizationName pgtype.Text        `json:"organization_name"`
	OrganizationUrl  pgtype.Text        `json:"organization_url"`
	PublicProfile    bool               `json:"public_profile"`
	UrlSlug          pgtype.Text        `json:"url_slug"`
	Flags            *json.RawMessage   `json:"flags"`
	CreatedOn        pgtype.Timestamptz `json:"created_on"`
	ModifiedOn       pgtype.Timestamptz `json:"modified_on"`
	StripeCustomerID pgtype.Text        `json:"stripe_customer_id"`
}

type LogScore struct {
	ID         int64              `json:"id"`
	MonitorID  pgtype.Int8        `json:"monitor_id"`
	ServerID   int64              `json:"server_id"`
	Ts         pgtype.Timestamptz `json:"ts"`
	Score      float64            `json:"score"`
	Step       float64            `json:"step"`
	Offset     pgtype.Float8      `json:"offset"`
	Rtt        pgtype.Int4        `json:"rtt"`
	Attributes pgtype.Text        `json:"attributes"`
}

type Monitor struct {
	ID            int64                 `json:"id"`
	IDToken       pgtype.Text           `json:"id_token"`
	Type          MonitorsType          `json:"type"`
	UserID        pgtype.Int8           `json:"user_id"`
	AccountID     pgtype.Int8           `json:"account_id"`
	Hostname      string                `json:"hostname"`
	Location      string                `json:"location"`
	Ip            pgtype.Text           `json:"ip"`
	IpVersion     NullMonitorsIpVersion `json:"ip_version"`
	TlsName       pgtype.Text           `json:"tls_name"`
	ApiKey        pgtype.Text           `json:"api_key"`
	Status        MonitorsStatus        `json:"status"`
	Config        string                `json:"config"`
	ClientVersion string                `json:"client_version"`
	LastSeen      pgtype.Timestamptz    `json:"last_seen"`
	LastSubmit    pgtype.Timestamptz    `json:"last_submit"`
	CreatedOn     pgtype.Timestamptz    `json:"created_on"`
	DeletedOn     pgtype.Timestamptz    `json:"deleted_on"`
	IsCurrent     pgtype.Bool           `json:"is_current"`
}

type Server struct {
	ID             int64              `json:"id"`
	Ip             string             `json:"ip"`
	IpVersion      ServersIpVersion   `json:"ip_version"`
	UserID         pgtype.Int8        `json:"user_id"`
	AccountID      pgtype.Int8        `json:"account_id"`
	Hostname       pgtype.Text        `json:"hostname"`
	Stratum        pgtype.Int2        `json:"stratum"`
	InPool         int16              `json:"in_pool"`
	InServerList   int16              `json:"in_server_list"`
	Netspeed       int64              `json:"netspeed"`
	NetspeedTarget int64              `json:"netspeed_target"`
	CreatedOn      pgtype.Timestamptz `json:"created_on"`
	UpdatedOn      pgtype.Timestamptz `json:"updated_on"`
	ScoreTs        pgtype.Timestamptz `json:"score_ts"`
	ScoreRaw       float64            `json:"score_raw"`
	DeletionOn     pgtype.Date        `json:"deletion_on"`
	Flags          string             `json:"flags"`
}

type ServerScore struct {
	ID                       int64              `json:"id"`
	MonitorID                int64              `json:"monitor_id"`
	ServerID                 int64              `json:"server_id"`
	ScoreTs                  pgtype.Timestamptz `json:"score_ts"`
	ScoreRaw                 float64            `json:"score_raw"`
	Stratum                  pgtype.Int2        `json:"stratum"`
	Status                   ServerScoresStatus `json:"status"`
	QueueTs                  pgtype.Timestamptz `json:"queue_ts"`
	CreatedOn                pgtype.Timestamptz `json:"created_on"`
	ModifiedOn               pgtype.Timestamptz `json:"modified_on"`
	ConstraintViolationType  pgtype.Text        `json:"constraint_violation_type"`
	ConstraintViolationSince pgtype.Timestamptz `json:"constraint_violation_since"`
	LastConstraintCheck      pgtype.Timestamptz `json:"last_constraint_check"`
	PauseReason              pgtype.Text        `json:"pause_reason"`
}
