#!/bin/bash

BASE=$1
BUILD=$2
DIR=$3

set -euo pipefail

if [ -z "$DIR" ]; then
  echo run with $0 NAME BUILD_NUMBER DIR
  exit 2
fi

mkdir -p $DIR

BASE=https://geodns.bitnames.com/${BASE}/builds/${BUILD}

files=`curl -sSf ${BASE}/checksums.txt | sed 's/^[a-f0-9]*[[:space:]]*//'`
metafiles="checksums.txt metadata.json CHANGELOG.md artifacts.json"

for f in $metafiles; do
  url=$BASE/$f
  echo downloading $url
  curl --remove-on-error -sSfRo $DIR/$f $url || true
done


for f in $files; do
  url=$BASE/$f
  echo downloading $url
  curl --remove-on-error -sSfRo $DIR/$f $url
done
